//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contract
    {
        public int ID { get; set; }
        public string Code { get; set; }
        public string ProductName { get; set; }
        public Nullable<decimal> InsuranceFee { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> EffectiveDate { get; set; }
        public Nullable<System.DateTime> NextPaymentDate { get; set; }
        public Nullable<System.DateTime> LatestPaymentDate { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public Nullable<decimal> ValueRefundedToAdvance { get; set; }
        public Nullable<decimal> AdvancePayment { get; set; }
        public Nullable<decimal> RTBT { get; set; }
        public Nullable<decimal> QLDK { get; set; }
        public Nullable<decimal> HuyHD { get; set; }
        public string TVVCode { get; set; }
        public string TVV { get; set; }
        public string DataComplete { get; set; }
        public string NMBHCode { get; set; }
        public string DiaChiHienTai { get; set; }
        public string TelMobile { get; set; }
        public string TelCompany { get; set; }
        public string TelHome { get; set; }
        public string VanPhong { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string DeleteFlg { get; set; }
        public string CustomerCMND { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string City { get; set; }
        public string District { get; set; }
        public string CustomerName { get; set; }
        public string DKDP { get; set; }
        public Nullable<int> ParentID { get; set; }
        public string Relation { get; set; }
        public string Loai { get; set; }
        public Nullable<decimal> PhiBaoHiem { get; set; }
        public Nullable<System.DateTime> NgayKetThucDongPhi { get; set; }
        public Nullable<System.DateTime> NgayDaoHan { get; set; }
        public string CustomerCode { get; set; }
        public string NTH { get; set; }
    }
}
